import Head from "next/head";
import styles from "@/styles/Home.module.scss";

import Image from "next/image";

export default function LandingPage() {
  return (
    <>
      <Head>
        <title>Bits & Bots</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main_landingPage}>
        -----------------------------------------------
        <video src={"/public/videos/background.mp4"} />
      </main>
    </>
  );
}
